# Generated by Django 5.0.3 on 2024-06-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Single-Family Home', 'Single-Family Home'), ('Condominium', 'Condominium'), ('TownHouse', 'TownHouse'), ('Apartment', 'Apartment'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex'), ('Vaccant-Land', 'Vaccant-Land'), ('Commercial Property', 'Commercial Property'), ('Industrial Property', 'Industrial Property'), ('Agricultural Property', 'Agricultural Property'), ('Mixed-Use Property', 'Mixed-Use Property'), ('TimeShare', 'TimeShare'), ('Cooperative', 'Cooperative'), ('Mobile Home', 'Mobile Home')], max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('location', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField(blank=True)),
                ('bathrooms', models.IntegerField(blank=True)),
                ('sqft', models.IntegerField()),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Renovated', 'Renovated'), ('Fixer-Upper', 'Fixed-Upper'), ('Luxury', 'Luxury'), ('Furnished', 'Furnished')], default='Brand New', max_length=100)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.category')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='properties.property')),
            ],
        ),
    ]
