# Generated by Django 5.0.6 on 2024-07-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_property_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
