# Generated by Django 5.0.6 on 2024-07-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name': 'PropertyImages', 'verbose_name_plural': 'PropertyImages'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
